import { Inter, Aclonica } from "next/font/google";
import { NavBar } from "../../components";
import "bootstrap/dist/css/bootstrap.min.css";

const inter = Aclonica({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "AGROVEPAL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
